package com.eugeneburak.trycatch.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import javax.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "trycatch_user_card")
public class TryCatchUser {

  @Id
  @DynamoDBHashKey @DynamoDBAutoGeneratedKey private String id;

  @NotBlank
  @DynamoDBAttribute(attributeName = "email")
  private String email;

  @NotBlank
  @DynamoDBAttribute(attributeName = "clientid")
  @DynamoDBIndexHashKey(globalSecondaryIndexNames = "clientid-index")
  private String clientId;

  @NotBlank
  @DynamoDBAttribute(attributeName = "card_number")
  private String cardNumber;
}
